apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db
spec:
  volumes:
  - name: postgres-storage
    emptyDir: {}
    
  containers:
    - name: db
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: todo_db
      ports:
        - containerPort: 5432