apiVersion: v1
kind: Pod
metadata:
  name: log-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: producer
      image: busybox
      command: ["/bin/sh","-c"]
      args:
        - while true; do date >> /data/log.txt; sleep 2; done
      volumeMounts:
        - name: shared-data
          mountPath: /data

    - name: consumer
      image: busybox
      command: ["/bin/sh","-c"]
      args:
        - tail -f /data/log.txt
      volumeMounts:
        - name: shared-data
          mountPath: /data