apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  volumes:
    - name: logs-volume
      emptyDir: {}

  containers:
    - name: web
      image: fastapi-k8s:v2
      imagePullPolicy: IfNotPresent
      env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@db-service:5432/todo_db
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: logs-volume
          mountPath: /logs